[build]
  command = "npm run build"
  publish ="/build"
  base = "/"

[[headers]]
  for = "https://app.netlify.app"
  [headers.values]
    Access-Control-Allow-Origin= "https://connectchattingapp.netlify.app"
    Access-Control-Allow-Credentials="true"

    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS,PATCH"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200